device: "cuda"  # or "cpu"
num_workers: 4
data_url: "https://mobilithek.info/offers/605778370199691264"
audio_path: "data/audio_files"
processed_path: "data/processed"
db_path: "data/metadata.db"
labels_path: "labels"
target_sr: 16000
filter_cutoff: 20
concat_duration: 1800  # 30min in seconds
mlflow:
  tracking_uri: "sqlite:///mlruns/mlruns.db"
  experiment_name: "audrok_pipeline"