stages:
  decoding_xml_to_wav:
    cmd: python -m pipeline process-xml-files 
      --input-folder data/xml_input 
      --output-folder data/processed/extracted_wav
    deps:
    - data/xml_input
    - pipeline/decode_xml_to_wav.py
    outs:
    - data/processed/extracted_wav

  downsampling_audio:
    cmd: python -m pipeline downsample-audio 
      --input-folder data/processed/extracted_wav 
      --output-folder data/processed/downsampled_wav
      --target-sr 16000
    deps:
    - data/processed/extracted_wav 
    - pipeline/downsample_wav.py
    outs:
    - data/processed/downsampled_wav

  filtering_outdoor:
    cmd: python -m pipeline highpass-filter 
      --input-folder data/processed/downsampled_wav
      --output-folder data/processed/filtered_outdoor_wav
      --cutoff-freq 20
      --sample-rate 16000
    deps:
    - data/processed/downsampled_wav
    - pipeline/filter_outdoor.py
    outs:
    - data/processed/filtered_outdoor_wav

  extracting_sound_data:
    cmd: python -m pipeline analyze-wav-files
      --input-folder data/processed/filtered_outdoor_wav
      --output-folder data/processed/wav_sound_metadata
    deps:
    - data/processed/filtered_outdoor_wav
    - pipeline/extract_sound_data_from_wav.py
    outs:
    - data/processed/wav_sound_metadata/wav_metadata.csv

  concatenating_segments:
    cmd: python -m pipeline concatenate-audio 
      --input-folder data/processed/filtered_outdoor_wav
      --output-folder data/processed/concatenated_wav_segments
      --metadata-path data/processed/wav_sound_metadata/wav_metadata.csv
      --target-duration 1800
      --tolerance 180
    deps:
    - data/processed/filtered_outdoor_wav
    - data/processed/wav_sound_metadata/wav_metadata.csv
    - pipeline/concatenate_into_segments.py
    outs:
    - data/processed/concatenated_wav_segments

  preparing_recording_positions:
    cmd: python -m pipeline generate-labels 
      --input-folder data/processed/concatenated_wav_segments
      --output-folder labels/recording_positions
      --metadata-path data/processed/wav_sound_metadata/wav_metadata.csv
    deps:
    - data/processed/concatenated_wav_segments
    - data/processed/wav_sound_metadata/wav_metadata.csv
    - pipeline/prepare_recording_positions.py
    outs:
    - labels/recording_positions

